In [1]:
range(0,5)

range(0, 5)

In [2]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,5,2))

[0, 2, 4]

In [6]:
list1 = [1,3,5,7,9]
list2 = [2,4,6,8,10]

In [7]:
list1 * list2


TypeError: can't multiply sequence by non-int of type 'list'

In [8]:
new_list = []
for i in range(len(list1)):
    x = list1[i]*list2[i]
    new_list.append(x)
new_list

[2, 12, 30, 56, 90]

In [1]:
import numpy as np

In [10]:
x = np.array([1,3,5,7,9])
x

array([1, 3, 5, 7, 9])

In [11]:
y = np.array([2,4,6,8,10])
y

array([ 2,  4,  6,  8, 10])

In [12]:
print(type(x))

<class 'numpy.ndarray'>


In [13]:
x*y

array([ 2, 12, 30, 56, 90])

In [14]:
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [15]:
variable = [5.8,9,7,5]


In [16]:
print(type(variable[0]))
print(type(variable[1]))

<class 'float'>
<class 'int'>


In [17]:
new_variable = np.array([5.8,9,7,5])

In [18]:
new_variable

array([5.8, 9. , 7. , 5. ])

In [19]:
new_variable2 = np.array([5.8,9,7,5], dtype = "int")
new_variable2

array([5, 9, 7, 5])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,5), dtype = "int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
np.ones((2,3,4),dtype = "int")

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [61]:
np.full(8,5)

array([5, 5, 5, 5, 5, 5, 5, 5])

In [66]:
np.full((2,3),6,dtype = "float")

array([[6., 6., 6.],
       [6., 6., 6.]])

In [67]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
example = np.arange(3,10,dtype = "float")
example

array([3., 4., 5., 6., 7., 8., 9.])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
np.eye(3,2,dtype = "int")

array([[1, 0],
       [0, 1],
       [0, 0]])

In [30]:
np.eye(3,2,dtype = "bool")

array([[ True, False],
       [False,  True],
       [False, False]])

In [31]:
np.linspace(10,30,5)

array([10., 15., 20., 25., 30.])

In [32]:
np.random.rand(5)

array([0.20047305, 0.27697049, 0.79457025, 0.784123  , 0.01438223])

In [33]:
np.random.rand(2,3)

array([[0.06499668, 0.30696113, 0.21243947],
       [0.31893869, 0.00373991, 0.83453286]])

In [74]:
x = np.random.randn(5)
x

array([-1.79320157,  2.19282618,  0.64419268,  2.10079015,  0.89149157])

In [77]:
np.random.normal(3,5,(4,3))

array([[ 2.4083372 ,  3.692306  , -1.32936648],
       [11.2501908 ,  8.56120621,  3.31400278],
       [ 3.00179275,  5.76598357,  1.78325551],
       [11.01595139, -2.05817353, -0.36116631]])

In [114]:
np.random.randint(0,10,(4,4))

array([[1, 0, 8, 1],
       [3, 1, 6, 4],
       [9, 9, 8, 0],
       [6, 4, 8, 5]])

In [116]:
matrix = np.random.randint(10,50,(5,4))
matrix

array([[11, 39, 39, 46],
       [34, 21, 29, 44],
       [11, 40, 41, 35],
       [33, 31, 14, 36],
       [12, 46, 22, 25]])

In [117]:
matrix.ndim

2

In [118]:
matrix.shape

(5, 4)

In [119]:
matrix.size

20

In [120]:
matrix.dtype

dtype('int32')

In [123]:
example = np.arange(1,16)
example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [128]:
example.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [130]:
array = example.reshape((1,15))
array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [131]:
example.ndim

1

In [132]:
array.ndim

2

In [134]:
array = np.random.randint(0,50,10)
array

array([ 8, 23, 40, 48, 39, 18, 27, 44, 42, 43])

In [137]:
array.max()

48

In [138]:
array.argmax()

3

In [140]:
array2 = np.random.randint(0,50,(4,3))
array2

array([[37, 35, 44],
       [14, 31, 46],
       [20, 24,  6],
       [ 5,  6, 35]])

In [141]:
array2.max()

46

In [144]:
array2.argmax()

5

In [146]:
print(array)
array.min()

[ 8 23 40 48 39 18 27 44 42 43]


8

In [147]:
array.argmin()

0

In [150]:
print(array2)
array2.min()

[[37 35 44]
 [14 31 46]
 [20 24  6]
 [ 5  6 35]]


5

In [149]:
array2.argmin()

9

In [151]:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])
print(array1,array2)

[1 2 3 4] [5 6 7 8]


In [153]:
np.concatenate([array1,array2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [156]:
array3 = np.arange(1,7).reshape((2,3))
array3

array([[1, 2, 3],
       [4, 5, 6]])

In [157]:
array4 = np.array([[7,8,9],[10,11,12]])
array4

array([[ 7,  8,  9],
       [10, 11, 12]])

In [158]:
np.concatenate([array3,array4])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [163]:
print("array3: ",array3)
print("array4: ",array4)
np.concatenate([array3,array4],axis = 1)

array3:  [[1 2 3]
 [4 5 6]]
array4:  [[ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [165]:
print("array1: ",array1)
print("array3: ",array3)
np.concatenate([array1,array3])

array1:  [1 2 3 4]
array3:  [[1 2 3]
 [4 5 6]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [168]:
array5 = np.arange(1,11).reshape(5,2)
array5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [169]:
np.concatenate([array3,array5])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [4]:
array = np.array([1,3,5,50,50,2,4,6])
array

array([ 1,  3,  5, 50, 50,  2,  4,  6])

In [14]:
np.split(array,[3,5])

[array([1, 3, 5]), array([50, 50]), array([2, 4, 6])]

In [19]:
x,y,z = np.split(array,[3,5])
print(x,y,z)

[1 3 5] [50 50] [2 4 6]


In [20]:
np.split(array,4)

[array([1, 3]), array([ 5, 50]), array([50,  2]), array([4, 6])]

In [24]:
np.split(array,5)

ValueError: array split does not result in an equal division

In [27]:

array = np.arange(20).reshape(5,4)
array


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [28]:
np.split(array,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [30]:
x,y,z = np.split(array,[1,3])
print(x,y,z)

[[0 1 2 3]] [[ 4  5  6  7]
 [ 8  9 10 11]] [[12 13 14 15]
 [16 17 18 19]]


In [37]:
np.split(array,[1,3],axis = 1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [38]:
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [39]:
np.hsplit(array,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [41]:
np.hsplit(array,[1,3])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [42]:
np.vsplit(array,5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [43]:
np.vsplit(array,[2,4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [44]:
variable = np.array([3,5,1,8,6,2,9])
variable

array([3, 5, 1, 8, 6, 2, 9])

In [45]:
np.sort(variable)

array([1, 2, 3, 5, 6, 8, 9])

In [47]:
example = np.random.normal(30,10,(4,4))
example

array([[29.83301955, 35.64820815, 41.38990588, 18.71708629],
       [27.74671576, 18.21870513, 33.12025506, 36.64504518],
       [16.81355264, 20.29211457, 30.75138855, 24.89514389],
       [24.13842218, 24.34253973, 19.92139391, 24.38247562]])

In [48]:
np.sort(example, axis = 0)

array([[16.81355264, 18.21870513, 19.92139391, 18.71708629],
       [24.13842218, 20.29211457, 30.75138855, 24.38247562],
       [27.74671576, 24.34253973, 33.12025506, 24.89514389],
       [29.83301955, 35.64820815, 41.38990588, 36.64504518]])

In [49]:
np.sort(example,axis = 1)

array([[18.71708629, 29.83301955, 35.64820815, 41.38990588],
       [18.21870513, 27.74671576, 33.12025506, 36.64504518],
       [16.81355264, 20.29211457, 24.89514389, 30.75138855],
       [19.92139391, 24.13842218, 24.34253973, 24.38247562]])

In [50]:
#from here in notes again
array = np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
array[4]

4

In [53]:
array[-1]

10

In [65]:
variable = np.linspace(5,45,9,dtype = "int").reshape(3,3)
variable

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
variable[1,1]

25

In [74]:
example = np.arange(10,20)
example

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [75]:
example[2:6]

array([12, 13, 14, 15])

In [76]:
example[3::2]

array([13, 15, 17, 19])

In [79]:
example[:7:3]

array([10, 13, 16])

In [80]:
array = np.arange(30).reshape(6,5)

In [81]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [86]:
array[2, :]

array([10, 11, 12, 13, 14])

In [87]:
array[2]

array([10, 11, 12, 13, 14])

In [88]:
array[0]

array([0, 1, 2, 3, 4])

In [90]:
array[:,2]

array([ 2,  7, 12, 17, 22, 27])

In [95]:
array[:,0]

array([ 0,  5, 10, 15, 20, 25])

In [99]:
array[1:4,0:3]

array([[ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

In [101]:
array[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [106]:
variable = np.array([0,1,2,3,7,5,6,9,8,9])
variable

array([0, 1, 2, 3, 7, 5, 6, 9, 8, 9])

In [112]:
variable[4] = 4
variable[7] = 7

In [113]:
variable

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
variable[0:5] = 10
variable

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [115]:
variable[5:]

array([5, 6, 7, 8, 9])

In [118]:
variable[5:] = 20,30,40,50,60
variable

array([10, 10, 10, 10, 10, 20, 30, 40, 50, 60])

In [161]:
example = np.linspace(10,90,9,dtype = "int").reshape(3,3)
example

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [162]:
example[1,1] = 100
example

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])

In [163]:
example[1,0] = 100.6
example

array([[ 10,  20,  30],
       [100, 100,  60],
       [ 70,  80,  90]])

In [164]:
example[:,2] = 100
example

array([[ 10,  20, 100],
       [100, 100, 100],
       [ 70,  80, 100]])

In [165]:
example[:3:2,:2] = 100
example

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [167]:
example[0] = 10,20,30
example

array([[ 10,  20,  30],
       [100, 100, 100],
       [100, 100, 100]])

In [168]:
fancy=np.arange(0,50,5)
fancy

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [169]:
fancy[3]

15

In [170]:
[fancy[1],fancy[3],fancy[5]]

[5, 15, 25]

In [171]:
indexes = [1,3,5]
fancy[indexes]

array([ 5, 15, 25])

In [173]:
array = np.array([1,3,5])
array

array([1, 3, 5])

In [175]:
fancy[array]

array([ 5, 15, 25])

In [176]:
fancy

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [183]:
newindexing = [-1]
fancy[newindexing]

array([45])

In [185]:
variable = np.zeros((10,10),dtype = "int")
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [186]:
variable.shape

(10, 10)

In [188]:
variable.shape[0]

10

In [190]:
row = variable.shape[0]
row

10

In [191]:
for i in range(row):
    variable[i] = i
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [194]:
list1 = variable[1:8:2,:]
list1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [195]:
list1 = [1,3,5,7]
variable[list1]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [196]:
list2 = [8,5,2,7,3]
variable[list2]

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [198]:
example = np.arange(1,17).reshape(4,4)
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [203]:
#important as we are taking rows in first inner square brackets
example[[0,3],[1,2]]

array([ 2, 15])

In [204]:
row = [0,2,3,1]
column = [3,0,2,1]
example[row,column]

array([ 4,  9, 15,  6])

In [207]:
example = np.arange(1,17).reshape(4,4)
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [208]:
example[1,[1,3]]

array([6, 8])

In [209]:
example[[0,3],1]

array([ 2, 14])

In [210]:
example[0:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [212]:
example[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

*COMPARISON OPERATORS*

In [17]:
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [19]:
array[array>5]

array([ 6,  7,  8,  9, 10])

In [20]:
condition = (array == 4)
array[condition]

array([4])

In [21]:
new_condition = (array != 8) & (array >= 6)
new_condition

array([False, False, False, False, False,  True,  True, False,  True,
        True])

In [22]:
array[new_condition]

array([ 6,  7,  9, 10])

In [23]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
array - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [25]:
array * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [27]:
array / 10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [28]:
((array*10)+20)/5

array([ 6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.])

In [29]:
array*array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [30]:
array/array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.subtract(array,2)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [32]:
np.multiply(array,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [33]:
 np.add(array,20)

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [34]:
np.divide(array,10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [36]:
array**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [37]:
np.power(array,3)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [38]:
np.sqrt(4)

2.0

In [40]:
np.sqrt(100)

10.0

In [41]:
array % 5

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [42]:
np.mod(array,5)

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [43]:
np.sin(180)

-0.8011526357338304

In [48]:
np.cos(180)

-0.5984600690578581

In [49]:
np.log(array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [50]:
np.log10(array)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [51]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
np.sum(array)

55

In [53]:
np.mean(array)

5.5

In [54]:
np.median(array)

5.5

In [55]:
np.min(array)

1

In [56]:
np.max(array)

10

In [64]:
np.std(array)

2.8722813232690143

In [59]:
np.var(array)

8.25

In [65]:
np.sqrt(np.var(array))

2.8722813232690143

In [76]:
coefficient = np.array([[2,1],[-3,6]])
coefficient

array([[ 2,  1],
       [-3,  6]])

In [77]:
output  = np.array([5,0])
output

array([5, 0])

In [78]:
np.linalg.solve(coefficient,output)

array([2., 1.])